interface Currencies {
  [key: string]: { name: string, image: any }
}

const assetsPath = "../../../assets"

export const currencies: Currencies = {
  BCH: { name: "Bitcoin Cash", image: require(assetsPath + "/crypto/bch.png") },
  BTC: { name: "Bitcoin", image: require(assetsPath + "/crypto/btc.png") },
  ETH: { name: "Ethereum", image: require(assetsPath + "/crypto/eth.png") },
  LTC: { name: "Litecoin", image: require(assetsPath + "/crypto/ltc.png") },
  XMR: { name: "Monero", image: require(assetsPath + "/crypto/xmr.png") },
  XRP: { name: "Ripple", image: require(assetsPath + "/crypto/xrp.png") },
  ZEC: { name: "Zcash", image: require(assetsPath + "/crypto/zec.png") },
  // "VERI": { name: "Veritaseum" },
  // "XLM": { name: "Stellar" },
  // "ZIL": { name: "Zilliqa" },
  // "ICN": { name: "Iconomi" },
  // "BTCD": { name: "BitcoinDark" },
  // "SALT": { name: "SALT" },
  // "KMD": { name: "Komodo" },
  // "XRL": { name: "Rialto" },
  // "PPT": { name: "Populous" },
  // "BRD": { name: "Bread" },
  // "SNOV": { name: "Snovio" },
  // "WAN": { name: "Wanchain" },
  // "OMG": { name: "OmiseGo" },
  // "NXS": { name: "Nexus" },
  // "QASH": { name: "QASH" },
  // "ARK": { name: "Ark" },
  // "REN": { name: "Republic Protocol" },
  // "LSK": { name: "Lisk" },
  // "GNO": { name: "Gnosis" },
  // "DOGE": { name: "Dogecoin" },
  // "ZCL": { name: "Zclassic" },
  // "IOTA": { name: "IOTA" },
  // "AST": { name: "AirSwap" },
  // "DGD": { name: "DigixDAO" },
  // "SNT": { name: "Status" },
  // "NEBL": { name: "Neblio" },
  // "LINK": { name: "ChainLink" },
  // "ICX": { name: "ICON" },
  // "ELF": { name: "aelf" },
  // "RDN": { name: "Raiden Network Token" },
  // "TRX": { name: "Tron" },
  // "BQX": { name: "Bitquence" },
  // "RDD": { name: "Reddcoin" },
  // "SUB": { name: "Substratum" },
  // "PRO": { name: "Propy" },
  // "OPT": { name: "Opus" },
  // "GAS": { name: "Gas" },
  // "MAID": { name: "MaidSafeCoin" },
  // "WTC": { name: "Waltonchain" },
  // "BCN": { name: "Bytecoin" },
  // "NMR": { name: "Numeraire" },
  // "DENT": { name: "Dent" },
  // "BNB": { name: "Binance Coin" },
  // "NANO": { name: "Nano" },
  // "ADA": { name: "Cardano" },
  // "REP": { name: "Augur" },
  // "NEO": { name: "NEO" },
  // "PAY": { name: "TenX" },
  // "QSP": { name: "Quantstamp" },
  // "QTUM": { name: "Qtum" },
  // "QRL": { name: "Quantum Resistant Ledger" },
  // "BTG": { name: "Bitcoin Gold" },
  // "NXT": { name: "NXT" },
  // "BTS": { name: "BitShares" },
  // "EOS": { name: "EOS" },
  // "USDT": { name: "Tether" },
  // "WAVES": { name: "Waves" },
  // "CVC": { name: "Civic" },
  // "GNT": { name: "Golem" },
  // "KNC": { name: "Kyber Network" },
  // "SYS": { name: "Syscoin" },
  // "ETC": { name: "Ethereum Classic" },
  // "MANA": { name: "Decentraland" },
  // "TNB": { name: "Time New Bank" },
  // "SC": { name: "Siacoin" },
  // "AION": { name: "Aion" },
  // "FCT": { name: "Factom" },
  // "ARDR": { name: "Ardor" },
  // "BTM": { name: "Bitmark" },
  // "XVG": { name: "Verge" },
  // "POLY": { name: "Polymath Network" },
  // "WAX": { name: "WAX" },
  // "STEEM": { name: "Steem" },
  // "ONT": { name: "Ontology" },
  // "REQ": { name: "Request Network" },
  // "BNT": { name: "Bancor Network Token" },
  // "PIVX": { name: "PIVX" },
  // "POWR": { name: "Power Ledger" },
  // "MONA": { name: "MonaCoin" },
  // "DCR": { name: "Decred" },
  // "XDN": { name: "DigitalNote" },
  // "ZRX": { name: "0x" },
  // "XEM": { name: "NEM" },
  // "DASH": { name: "Dash" },
  // "DGB": { name: "DigiByte" },
  // "STRAT": { name: "Stratis" },
  // "ENG": { name: "Enigma" },
  // "HSR": { name: "HShare" },
  // "FUN": { name: "FunFair" },
  // "GAME": { name: "GameCredits" },
  // "BAT": { name: "Basic Attention Token" },
  // "SAN": { name: "Santiment Network Token" },
  // "APPC": { name: "AppCoins" },
  // "REBL": { name: "Rebellious" }
}
